"""empty message

Revision ID: 18331e7a7a26
Revises: 9980fba589e3
Create Date: 2019-06-27 22:15:35.491967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18331e7a7a26'
down_revision = '9980fba589e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'note')
    # ### end Alembic commands ###
