"""init migration

Revision ID: 9980fba589e3
Revises: 
Create Date: 2019-06-15 00:10:59.477024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9980fba589e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
